#### Amazon Books ####
# KMPN # Not Provided
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py ../configs/KMPN_books.jsonnet --mode train --experiment_name KMPN_AmazonBooks_MetaPreferences_64_PCA_0.5  --lr 0.001 --batch_size 65536 --epochs 2000 --scheduler linear --module_type PCA_DISTANCE_COR INDEPENDENT_RELATION_EMB --clipping 10 --node_dropout --negative_sampling_mode inversed_ratio --pca_ratio 0.5 --num_meta_preferences 64
# NRMS Provided
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py ../configs/NRMS_BERT_books.jsonnet --mode train --experiment_name NRMS_BERT_Amazon_LR_0.0001_Layer_3_History_10_NoAttMask  --lr 0.0001 --batch_size 64 --test_batch_size 64 --epochs 1000 --clipping 10 --num_history 10 --freeze_transformer_layers 9
# CKMPN Provided
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py ../configs/KMPN_books.jsonnet --mode train --experiment_name KMPN_AmazonBooks_MetaPreferences_64_PCA_0.5_CrossSystemContrastiveLearning_0.1  --lr 0.001 --batch_size 65536 --epochs 2000 --scheduler linear --module_type PCA_DISTANCE_COR INDEPENDENT_RELATION_EMB NRMS_BERT_EMB NRMS_BERT_EMB_CROSS_SYSTEM --clipping 10 --node_dropout --negative_sampling_mode inversed_ratio --pca_ratio 0.5 --load_transformer_path ../Experiments/NRMS_BERT_Amazon_LR_0.0001_Layer_3_History_10_NoAttMask/train/saved_model/model_175.pth.tar  --dataset_name NRMS_BERT_Amazon_LR_0.0001_Layer_3_History_10_NoAttMask_EPOCH_175  --cross_system_loss_decay 0.1 --num_meta_preferences 64 --regenerate_transformer_data

#### Movie 19d ####
# KMPN # Not Provided
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py ../configs/KMPN_movie_19d.jsonnet --mode train --enable_validation --experiment_name MOVIE_19d_ColdStart_KMPN_Batch_8192x8_lr_linear_5e-4_epoch_1000_PCA_0.5_MetaPreferences_64  --lr 0.0005 --batch_size 65536 --epochs 1000 --scheduler linear --dataset_name movie_dataset_19d_ColdStart --load_num_movies 50000 --load_num_users 200000 --split_cold_start --cold_start_ratio 0.03 --negative_sampling_mode inversed_ratio --clipping 10 --node_dropout --num_meta_preferences 64 --module_type INDEPENDENT_RELATION_EMB PCA_DISTANCE_COR --pca_ratio 0.5
# NRMS # Provided
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py ../configs/NRMS_BERT_movies_19d.jsonnet --mode train --enable_validation --experiment_name NRMS_BERT_Movie_19d_ColdStart_LR_0.0005_Layer_1_History_30_NoAttMask  --lr 0.0005 --batch_size 64 --test_batch_size 64 --epochs 1000 --dataset_name movie_dataset_19d_ColdStart --load_num_movies 50000 --load_num_users 200000 --num_history 30 --freeze_transformer_layers 11 --split_cold_start --cold_start_ratio 0.03
# CKMPN # Not Provided
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py ../configs/KMPN_movie_19d.jsonnet --mode train --enable_validation --experiment_name MOVIE_19d_ColdStart_KMPN_Batch_8192x8_lr_linear_5e-4_epoch_1000_PCA_0.5_MetaPreferences_64_CrossProductSystem_0.01_valid_test  --lr 0.0005 --batch_size 65536 --epochs 1000 --scheduler linear --dataset_name movie_dataset_19d_ColdStart --load_num_movies 50000 --load_num_users 200000 --split_cold_start --cold_start_ratio 0.03 --negative_sampling_mode inversed_ratio --clipping 10 --node_dropout --num_meta_preferences 64 --module_type INDEPENDENT_RELATION_EMB PCA_DISTANCE_COR NRMS_BERT_EMB NRMS_BERT_EMB_CROSS_SYSTEM --pca_ratio 0.5 --cross_system_loss_decay 0.01 --load_transformer_path /home/v-weizhelin/projects/intern-weizhe/Experiments/NRMS_BERT_Movie_19d_ColdStart_LR_0.0005_Layer_1_History_30_NoAttMask/train/saved_model/model_46.pth.tar

#### Movie 39d ####
# NRMS # Provided
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python main.py ../configs/NRMS_BERT_movies_39d.jsonnet --mode train --experiment_name NRMS_BERT_Movie_39d_ColdStart_LR_0.0005_Layer_1_History_30_NoAttMask  --lr 0.0005 --batch_size 64 --test_batch_size 64 --epochs 1000 --dataset_name movie_dataset_39d_ColdStart --load_num_movies 50000 --load_num_users 200000 --num_history 30 --freeze_transformer_layers 11 --split_cold_start --cold_start_ratio 0.03
